# Generated by Django 5.2.8 on 2025-11-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='Other', max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], default='Remote', max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField(help_text='Short description for careers listing page')),
                ('detailed_description', models.TextField(help_text='Full detailed description for job detail page')),
                ('responsibilities', models.TextField(blank=True, help_text='Enter each responsibility on a new line')),
                ('required_qualifications', models.TextField(help_text='Enter each qualification on a new line')),
                ('preferred_qualifications', models.TextField(blank=True, help_text='Enter each qualification on a new line')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from careers page')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
