# Generated by Django 5.2.8 on 2025-11-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, help_text='Short description for careers listing page (auto-generated)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='preferred_qualifications',
            field=models.TextField(blank=True, default='', help_text='Enter each qualification on a new line'),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_qualifications',
            field=models.TextField(blank=True, default='', help_text='Enter each qualification on a new line'),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, default='', help_text='Enter each responsibility on a new line'),
        ),
    ]
